# Generated by Django 4.1.5 on 2023-02-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='UserAccountPics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSSTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(default='', max_length=50)),
                ('descriptionArm', models.TextField(blank=True)),
                ('descriptionRus', models.TextField(blank=True)),
                ('descriptionEng', models.TextField(blank=True)),
                ('syntax', models.TextField(blank=True, default='')),
                ('letter', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CSSTagsAttrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(default='', max_length=50)),
                ('descriptionArm', models.TextField(blank=True)),
                ('descriptionRus', models.TextField(blank=True)),
                ('descriptionEng', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTMLTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(default='', max_length=50)),
                ('descriptionArm', models.TextField(blank=True)),
                ('descriptionRus', models.TextField(blank=True)),
                ('descriptionEng', models.TextField(blank=True)),
                ('syntax', models.TextField(blank=True, default='')),
                ('example', models.TextField(blank=True, default='')),
                ('typeArm', models.CharField(blank=True, default='', max_length=70)),
                ('typeRus', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='HTMLTagsAttrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleArm', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('titleRus', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('titleEng', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('descriptionArm', models.TextField(blank=True)),
                ('descriptionRus', models.TextField(blank=True)),
                ('descriptionEng', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='lessonsImages')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NYXCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
