# Generated by Django 4.1.5 on 2023-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleArm', models.CharField(max_length=255, unique=True)),
                ('descriptionArm', models.TextField()),
                ('descriptionRus', models.TextField()),
                ('descriptionEng', models.TextField()),
            ],
        ),
    ]
