# Generated by Django 4.1.5 on 2023-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='titleEng',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='titleRus',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='titleArm',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
