# Generated by Django 4.1.5 on 2023-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lessons_titleeng_lessons_titlerus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='descriptionArm',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='descriptionEng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='descriptionRus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='titleArm',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='titleEng',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='titleRus',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
