# Generated by Django 4.1.5 on 2023-01-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lessons_descriptionarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='image',
            field=models.ImageField(blank=True, upload_to='lessonsImages'),
        ),
    ]
