# Generated by Django 4.1.5 on 2023-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lessons_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(default='', max_length=50)),
                ('descriptionArm', models.TextField(blank=True)),
                ('descriptionRus', models.TextField(blank=True)),
                ('descriptionEng', models.TextField(blank=True)),
                ('syntax', models.TextField(blank=True, default='')),
            ],
        ),
    ]
