# Generated by Django 4.1.5 on 2023-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_htmltags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTagsAttrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
