# Generated by Django 4.1.5 on 2023-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_htmltagsattrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltags',
            name='example',
            field=models.TextField(blank=True, default=''),
        ),
    ]
