# Generated by Django 4.1.5 on 2023-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_htmltags_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltags',
            name='typeArm',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='htmltags',
            name='typeRus',
            field=models.CharField(default='', max_length=70),
        ),
    ]
