# Generated by Django 4.1.5 on 2023-01-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_htmltags_typearm_htmltags_typerus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltags',
            name='typeArm',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
