# Generated by Django 4.1.5 on 2023-01-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_htmltags_typearm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(default='', max_length=50)),
                ('descriptionArm', models.TextField(blank=True)),
                ('descriptionRus', models.TextField(blank=True)),
                ('descriptionEng', models.TextField(blank=True)),
                ('syntax', models.TextField(blank=True, default='')),
                ('example', models.TextField(blank=True, default='')),
                ('typeArm', models.CharField(blank=True, default='', max_length=70)),
                ('typeRus', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CSSTagsAttrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(default='', max_length=50)),
                ('descriptionArm', models.TextField(blank=True)),
                ('descriptionRus', models.TextField(blank=True)),
                ('descriptionEng', models.TextField(blank=True)),
                ('CSSTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.csstags')),
            ],
        ),
    ]
